#!/bin/bash

yaourt -Syu ntfs-3g pluseadio pluseaudio-alsa pasystray-git teamviewer xorg xfce4 xfce4-goodies firefox flashplugin vlc file-roller filezilla gparted git brasero skype paprefs pavucontrol networkmanager network-manager-applet bluez blueman gksu thunderbird python-pyparted python-configobj python python-gobject python-dbus python-cairo python-yaml
