[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Ambiance-Flat-zFusion-Graphite
Comment=Ambiance Flat, A Redesigned Modern & Flat, Ambiance Based Theme W/New Colors By RAVEfinity.com (14.04)
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Ambiance-Flat-zFusion-Graphite
MetacityTheme=Ambiance-Flat-zFusion-Graphite
IconTheme=Vibrancy-Dark-Graphite
CursorTheme=DMZ-White
ButtonLayout=close,minimize,maximize:
